# Generated by Django 2.2 on 2019-06-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('Bank', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('commision', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('session_start_month', models.CharField(blank=True, max_length=10, null=True)),
                ('session_end_month', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('Bank', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('front_end', models.BooleanField(default=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Chain')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('create', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=True)),
                ('update', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('type', models.CharField(default='tree', max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.School')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolProfileRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SchoolRole')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.School')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ChainRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('create', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=True)),
                ('update', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('type', models.CharField(default='tree', max_length=50)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Chain')),
            ],
        ),
        migrations.CreateModel(
            name='ChainProfileRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Chain')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ChainRole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
