# Generated by Django 2.2 on 2019-06-24 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20190625_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('numaric_name', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='media/resume/')),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('event', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('place', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('on_web', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('grade', models.CharField(max_length=30)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('marks_from', models.IntegerField()),
                ('marks_to', models.IntegerField()),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('extra_day', models.IntegerField(default=0)),
                ('fine', models.FloatField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('on_web', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('news', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('on_web', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('notice', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('on_web', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('salary', models.FloatField()),
                ('allowance', models.FloatField()),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('stop_name', models.CharField(blank=True, max_length=30, null=True)),
                ('stop_fare', models.FloatField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Class')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('privious_school', models.CharField(max_length=50)),
                ('privious_class', models.CharField(max_length=20)),
                ('tc', models.FileField(blank=True, null=True, upload_to='media/tc/')),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('subject', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('subject_code', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('book', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('is_compalsory', models.BooleanField(default=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Profile')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('Name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('user_to_meet', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('number_palte', models.CharField(blank=True, max_length=30, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=30, null=True)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TransportMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Profile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='media/syllabus/')),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttandance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('attandance', models.CharField(max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Rutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Vehicle'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('room', models.CharField(max_length=30)),
                ('seat', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('remark', models.CharField(max_length=150)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostelMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gurdian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Class')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateField()),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Class')),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ExamTerm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttandance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('attandance', models.CharField(default='Present', max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ExamSchedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Payroll'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Employee'),
        ),
        migrations.CreateModel(
            name='Attandance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('attandance', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(max_length=30)),
                ('deadline', models.DateField()),
                ('assignment', models.FileField(blank=True, null=True, upload_to='media/assignment/')),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Class')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('Amount', models.FloatField()),
                ('is_income', models.BooleanField(default=False)),
                ('payment_category', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('paid_status', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('paid_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Profile')),
            ],
        ),
    ]
